title: Anti-Veil                # replace with your brand name
description: Disillusion  # replace with your tagline
url: "https://yourusername.github.io"
baseurl: ""
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
